name <- readline("Enter your name: ")
age <- as.integer(readline("Enter your age: "))
cat("Your name is:", name, "\n")
cat("Your age is:", age, "\n")
cat("R version:", R.version$version.string, "\n")
